### ISSUE TITLE
Update JSON data

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/mod-wildfire-maps#14]
There are new externalizable data available in 0.18.0

- [ ] Clean up traversibility mapping from strategic-map-movement-costs.json - ja2-stracciatella/ja2-stracciatella#1262
- [ ] Sector names (town and underground sectors) - ja2-stracciatella/ja2-stracciatella#1264
- [ ] Loading screens (town and underground sectors) - ja2-stracciatella/ja2-stracciatella#1182

**Comment by ja2-derek** [comment]
We should also convert `.json` to `.patch.json`, which should be more robust.
